export const heroProfile = {
  name: 'Amir Babaei',
  role: 'Senior Backend Developer',
  tagline: 'Backend engineer crafting scalable Laravel systems, APIs, automation, and resilient services.',
  intro:
    'Career Odyssey turns Amir\'s resume into a polished playable world where each monument represents a real chapter of his experience or education.',
  contact: {
    email: 'amirbabaei.dev@gmail.com',
    phone: '+90 534 336 2185',
    location: 'Istanbul, Turkey',
  },
  links: [
    {
      id: 'linkedin',
      label: 'LinkedIn',
      url: 'https://www.linkedin.com/in/amir-mohammad-babaei/',
      description: 'Professional profile and public career presence.',
      accent: '#7dd3fc',
    },
    {
      id: 'github',
      label: 'GitHub',
      url: 'https://github.com/amirbabaeii',
      description: 'Code samples, experiments, and public repositories.',
      accent: '#c084fc',
    },
  ],
};

export const milestones = [
  {
    id: 'arpm',
    category: 'experience',
    title: 'Senior Backend Developer',
    place: 'ARPM.co — New York, USA',
    period: 'Dec 2024 — Present',
    accent: '#7dd3fc',
    vibe: 'Distributed systems and delivery',
    bullets: [
      'Refactored legacy Laravel and PHP code to improve modularity, reuse, and maintainability.',
      'Worked on Docker-based service architecture and microservice reliability.',
      'Automated operational flows with CI/CD and Bash scripting.',
      'Collaborated with a multinational team building systems for global users.',
    ],
  },
  {
    id: 'ecomelk',
    category: 'experience',
    title: 'Senior Backend Developer',
    place: 'Ecomelk.com — Tehran, Iran',
    period: 'Jul 2022 — Nov 2024',
    accent: '#5eead4',
    vibe: 'Optimization, leadership, secure auth',
    bullets: [
      'Improved legacy performance by resolving N+1 queries and removing unnecessary dependencies.',
      'Led and collaborated with a small web development team.',
      'Built secure login flows including OTP and OAuth.',
      'Used APIs, queues, and message brokers for service-to-service communication.',
    ],
  },
  {
    id: 'drmobile',
    category: 'experience',
    title: 'Backend Developer',
    place: 'Drmobile.ir — Rasht, Iran',
    period: 'Dec 2021 — May 2022',
    accent: '#93c5fd',
    vibe: 'Clean architecture and testing',
    bullets: [
      'Integrated CMS and CRM systems through APIs.',
      'Applied repository, service, factory, and provider patterns in Laravel.',
      'Added feature and unit tests with PHPUnit.',
    ],
  },
  {
    id: 'arvan',
    category: 'experience',
    title: 'Backend Developer',
    place: 'Arvan Real Estate — Rasht, Iran',
    period: 'Aug 2021 — Dec 2021',
    accent: '#c4b5fd',
    vibe: 'APIs, caching, and speed',
    bullets: [
      'Built a lightweight PHP database layer and REST API for a React PWA.',
      'Improved server speed with better caching and configuration.',
    ],
  },
  {
    id: 'farmehr',
    category: 'experience',
    title: 'Full Stack Developer',
    place: 'Farmehr Rayaneh Co. — Rasht, Iran',
    period: 'Jul 2019 — Aug 2021',
    accent: '#f9a8d4',
    vibe: 'Product building and delivery',
    bullets: [
      'Built office automation systems with Laravel.',
      'Implemented Amazon S3 backup workflows.',
      'Created an e-commerce platform using React and Bootstrap.',
    ],
  },
  {
    id: 'freelance',
    category: 'experience',
    title: 'Full Stack Web Developer',
    place: 'Freelancer',
    period: 'Jul 2019 — Jul 2022',
    accent: '#fdba74',
    vibe: 'Independent execution and ecosystem breadth',
    bullets: [
      'Used Laravel Livewire, Sanctum, Jetstream, Voyager, and Spatie packages.',
      'Improved delivery consistency through better task management habits.',
    ],
  },
  {
    id: 'university',
    category: 'education',
    title: 'Bachelor of Computer Engineering',
    place: 'University of Guilan — Rasht, Iran',
    period: 'Oct 2019 — Mar 2024',
    accent: '#fde047',
    vibe: 'Algorithms and engineering foundations',
    bullets: [
      'Studied algorithms, data structures, mathematics, and statistics.',
      'Built a strong foundation in computer hardware and engineering concepts.',
    ],
  },
  {
    id: 'highschool',
    category: 'education',
    title: 'Diploma of Maths and Physics',
    place: 'Beheshti High School — Rasht, Iran',
    period: 'Oct 2015 — Jun 2019',
    accent: '#fca5a5',
    vibe: 'Analytical roots',
    bullets: ['Built a strong base in mathematics and physics.'],
  },
];
